### ISSUE TITLE
Interested?

### ISSUE THREAD

**Issue by RomkeVdMeulen** [Vevida/datagrid-demo#1]
We're trying to figure out the level of interest for this project. Do you think this datagrid is something you might want to use? What changes / features would you like to see?

**Comment by CD-UNCC** [comment]
Just getting started with it with a high level of interest. I'll report back once I've had some time to experiment

**Comment by BruceBissett** [comment]
Very interesting.  It looks to be quite useful.  Would it contain the ability to edit values inside the grid?

**Comment by RomkeVdMeulen** [comment]
No, but what you could do is implement your own editable value component and then render that inside the datagrid. E.g.:

```html
<require from="src/components/myinlineeditor"></require>

<datagrid rows.bind="myData">
    <column header="My Editable Field">
        <my-inline-editor value.bind="row.myValue" onSave.bind="parent.saveCallback">
        </my-inline-editor>
    </column>
</datagrid>
```

**Comment by ChefGrizzlyBear** [comment]
I use aurelia extensively and have had to build my own custom datagrids from scratch for each project. I haven't had the time to make it modular. It would be of very great value.

**Comment by seancull** [comment]
I am looking for a new platform for our apps ( old one is becoming legacy ) and the ability to drop in well documented components like these really does make a difference in our ranking of Aurelia.

**Comment by htxryan** [comment]
This would be great!
